services:
  database:
    image: postgres:15.2-alpine3.17
    container_name: minihorta-db
    restart: always
    mem_limit: 512mb
    environment:
      POSTGRES_DB: minihorta_db
      POSTGRES_PASSWORD: M1N1H0RT4_P4SSW0RD
      POSTGRES_USER: minihorta_admin
    ports:
      - 5440:5432
    volumes:
      - ./volumes/minihorta/db:/var/lib/postgresql/data